version: '3.8'

services:
  postgres-db-product:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: fiap-lanches-product
    ports:
      - "5434:5432"
    volumes:
      - postgres-db-product:/var/lib/postgresql/data
    networks:
      - fiap-lanchonet-network
  
  fiap-lanches-product-api:
    build:
     context: .
     dockerfile: ./Dockerfile
    hostname: fiap-lanches-product-api
    ports:
      - "8082:8082"
    volumes:
      - fiap-lanches-product-api:/var/lib/fiaplancher/data
    depends_on:
      - postgres-db-product
    networks:
      - fiap-lanchonet-network
        
networks:
  fiap-lanchonet-network:
    external: true

volumes:
  postgres-db-product:
    driver: local
  fiap-lanches-product-api:
    driver: local
